// app/(main)/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Sidebar2 from "@/components/Sidebar2";
import Player from "@/components/player";
import { PlayerProvider } from "@/app/context/Playercontext";
import { SessionWrapper } from "../SessionWrapper";
import { FileProvider } from "@/app/context/Filecontext";
import { SidebarProvider } from "@/app/context/SidebarContext";
import { GeneratedPlaylistProvider } from "@/app/context/GeneratedPlaylistContext";
import PathWatcher from "@/components/path/PathWatcher";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zound Mood",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} font-sans bg-black text-white h-screen `}
    >
      <SessionWrapper>
        <FileProvider>
          <PlayerProvider>
             <Header />
            <SidebarProvider>
              <PathWatcher />
              <div className="flex flex-col md:flex-row p-4 gap-4 h-auto md:h-[calc(100vh-5rem)]">
                <Sidebar />
                <GeneratedPlaylistProvider>
                  <main className="flex-1 bg-gradient-to-t from-black from-[10%] to-[#252525] mb-20 overflow-y-auto w-full h-full">
                    {children}
                  </main>
                </GeneratedPlaylistProvider>
                <Sidebar2 />
              </div>
            </SidebarProvider>
            <Player />
          </PlayerProvider>
        </FileProvider>
      </SessionWrapper>
    </div>
  );
}
