// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Sidebar2 from "@/components/Sidebar2";
import Player from "@/components/player";
import { PlayerProvider } from "@/app/context/Playercontext";
import { SessionWrapper } from "../SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="font-sans bg-black text-white h-screen overflow-hidden">
        <SessionWrapper>
          <PlayerProvider>
            <Header />

            <div className="flex p-4 gap-4 h-[calc(100vh-5rem)]">
              <Sidebar />
              <main className="flex-1 p-10 space-y-10 bg-gradient-to-t from-black from-[10%] to-[#252525] overflow-y-auto">
                {children}
              </main>
              <Sidebar2 />
            </div>

            <Player />
          </PlayerProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
